# Generated by Django 5.2.12 on 2026-03-19 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('routines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0, help_text='segundos totales')),
                ('status', models.CharField(choices=[('in_progress', 'En progreso'), ('completed', 'Completado'), ('abandoned', 'Abandonado')], default='in_progress', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('routine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='routines.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de entrenamiento',
                'verbose_name_plural': 'Sesiones de entrenamiento',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SessionSetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('reps_done', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_done', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_used', models.FloatField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercise')),
                ('workout_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routines.workoutset')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
    ]
