# Generated by Django 5.2.12 on 2026-03-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('completed', 'Completado'), ('skipped', 'Saltado')], default='planned', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrada de Calendario',
                'verbose_name_plural': 'Calendario',
                'ordering': ['-date'],
            },
        ),
    ]
