# Generated by Django 5.2.12 on 2026-03-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField(help_text='Minutos estimados')),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20)),
                ('category', models.CharField(choices=[('strength', 'Fuerza'), ('cardio', 'Cardio'), ('hiit', 'HIIT'), ('yoga', 'Yoga'), ('mobility', 'Movilidad'), ('custom', 'Personalizada')], default='strength', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, help_text='segundos', null=True)),
                ('weight', models.FloatField(blank=True, help_text='kg', null=True)),
                ('rest', models.PositiveSmallIntegerField(default=60, help_text='segundos de descanso')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
    ]
