# Generated by Django 5.2.12 on 2026-04-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trainer_request_pending',
            field=models.BooleanField(default=False, help_text='Solicitud de ser entrenador pendiente'),
        ),
    ]
