import type {
  User,
  Exercise,
  Routine,
  WorkoutSession,
  Conversation,
  ChatMessage,
  Post,
  Comment,
  Payment,
  Plan,
  CalendarDay,
} from './types';

// ─── USERS ────────────────────────────────────────────────────────────────────
export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Alex García',
    email: 'alex@fitpro.com',
    role: 'client',
    avatar: 'https://i.pravatar.cc/150?img=3',
    bio: 'Apasionado del fitness. Objetivo: ganar masa muscular.',
    weight: 78,
    height: 178,
    goal: 'Ganar masa muscular',
    trainerId: 't1',
    joinedAt: '2024-01-15',
  },
  {
    id: 't1',
    name: 'Carlos Mendez',
    email: 'carlos@fitpro.com',
    role: 'trainer',
    avatar: 'https://i.pravatar.cc/150?img=12',
    bio: 'Entrenador certificado. 8 años de experiencia.',
    weight: 85,
    height: 182,
    goal: 'Ayudar a mis clientes',
    joinedAt: '2023-06-01',
  },
  {
    id: 'u2',
    name: 'María López',
    email: 'maria@fitpro.com',
    role: 'client',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Corredora amateur. Buscando mejorar resistencia.',
    weight: 62,
    height: 165,
    goal: 'Mejorar resistencia cardiovascular',
    trainerId: 't1',
    joinedAt: '2024-02-10',
  },
  {
    id: 'u3',
    name: 'Juan Torres',
    email: 'juan@fitpro.com',
    role: 'client',
    avatar: 'https://i.pravatar.cc/150?img=8',
    bio: 'Principiante. Quiero perder peso.',
    weight: 95,
    height: 175,
    goal: 'Perder peso',
    trainerId: 't1',
    joinedAt: '2024-03-01',
  },
  {
    id: 'a1',
    name: 'Ana Ruiz',
    email: 'admin@fitpro.com',
    role: 'admin',
    avatar: 'https://i.pravatar.cc/150?img=9',
    bio: 'Administradora de la plataforma.',
    weight: 60,
    height: 168,
    goal: 'Gestionar la plataforma',
    joinedAt: '2023-01-01',
  },
];

// ─── EXERCISES ────────────────────────────────────────────────────────────────
export const MOCK_EXERCISES: Exercise[] = [
  {
    id: 'e1',
    name: 'Press de Banca',
    category: 'Fuerza',
    muscle: 'Pecho',
    difficulty: 'intermediate',
    description: 'Ejercicio compuesto para desarrollar el pecho, hombros y tríceps.',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    instructions: [
      'Acuéstate en el banco con los pies apoyados en el suelo.',
      'Agarra la barra con un agarre ligeramente más ancho que los hombros.',
      'Baja la barra controladamente hasta tocar el pecho.',
      'Empuja la barra hacia arriba hasta extender los brazos.',
    ],
  },
  {
    id: 'e2',
    name: 'Sentadilla',
    category: 'Fuerza',
    muscle: 'Piernas',
    difficulty: 'intermediate',
    description: 'Ejercicio fundamental para desarrollar fuerza en piernas y glúteos.',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    instructions: [
      'Posiciona la barra sobre los trapecios.',
      'Abre los pies al ancho de los hombros.',
      'Desciende doblando las rodillas hasta los 90 grados.',
      'Sube empujando con los talones.',
    ],
  },
  {
    id: 'e3',
    name: 'Peso Muerto',
    category: 'Fuerza',
    muscle: 'Espalda baja',
    difficulty: 'advanced',
    description: 'Ejercicio compuesto de alto impacto para toda la cadena posterior.',
    imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400',
    instructions: [
      'Colócate frente a la barra con los pies al ancho de las caderas.',
      'Agarra la barra con agarre pronado o mixto.',
      'Mantén la espalda recta y el core activado.',
      'Levanta la barra extendiendo caderas y rodillas simultáneamente.',
    ],
  },
  {
    id: 'e4',
    name: 'Pull-ups',
    category: 'Fuerza',
    muscle: 'Espalda',
    difficulty: 'intermediate',
    description: 'Dominadas para desarrollar la espalda y bíceps.',
    imageUrl: 'https://images.unsplash.com/photo-1590487988256-9ed24133863e?w=400',
    instructions: [
      'Cuelga de la barra con los brazos extendidos.',
      'Activa el core y los omóplatos.',
      'Sube hasta que la barbilla supere la barra.',
      'Baja de forma controlada.',
    ],
  },
  {
    id: 'e5',
    name: 'Cardio HIIT',
    category: 'Cardio',
    muscle: 'Cuerpo completo',
    difficulty: 'intermediate',
    description: 'Entrenamiento de intervalos de alta intensidad.',
    imageUrl: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=400',
    instructions: [
      '30 segundos de máximo esfuerzo.',
      '15 segundos de descanso.',
      'Repetir 8 veces.',
    ],
  },
  {
    id: 'e6',
    name: 'Plancha',
    category: 'Core',
    muscle: 'Abdomen',
    difficulty: 'beginner',
    description: 'Ejercicio isométrico para fortalecer el core.',
    imageUrl: 'https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=400',
    instructions: [
      'Apoya los antebrazos y puntas de los pies en el suelo.',
      'Mantén el cuerpo recto como una tabla.',
      'Activa el core y aguanta la posición.',
    ],
  },
  {
    id: 'e7',
    name: 'Remo con Mancuerna',
    category: 'Fuerza',
    muscle: 'Espalda',
    difficulty: 'beginner',
    description: 'Ejercicio unilateral para espalda alta y bíceps.',
    imageUrl: 'https://images.unsplash.com/photo-1530822847156-5df684ec5933?w=400',
    instructions: [
      'Apoya una mano y rodilla en el banco.',
      'Toma la mancuerna con la otra mano.',
      'Lleva el codo hacia atrás jalando la mancuerna.',
      'Baja de forma controlada.',
    ],
  },
  {
    id: 'e8',
    name: 'Curl de Bíceps',
    category: 'Fuerza',
    muscle: 'Bíceps',
    difficulty: 'beginner',
    description: 'Ejercicio de aislamiento para desarrollar los bíceps.',
    imageUrl: 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400',
    instructions: [
      'De pie, con mancuernas en cada mano.',
      'Sube las mancuernas doblando los codos.',
      'Contrae el bíceps en la parte superior.',
      'Baja de forma controlada.',
    ],
  },
];

// ─── ROUTINES ─────────────────────────────────────────────────────────────────
export const MOCK_ROUTINES: Routine[] = [
  {
    id: 'r1',
    name: 'Fuerza Superior A',
    description: 'Rutina enfocada en la parte superior del cuerpo con énfasis en pecho y espalda.',
    trainerId: 't1',
    userId: 'u1',
    exercises: [
      {
        exerciseId: 'e1',
        exercise: MOCK_EXERCISES[0],
        sets: [
          { reps: 10, weight: 60, rest: 90 },
          { reps: 8, weight: 70, rest: 90 },
          { reps: 6, weight: 75, rest: 120 },
        ],
      },
      {
        exerciseId: 'e4',
        exercise: MOCK_EXERCISES[3],
        sets: [
          { reps: 8, rest: 90 },
          { reps: 8, rest: 90 },
          { reps: 6, rest: 90 },
        ],
      },
      {
        exerciseId: 'e7',
        exercise: MOCK_EXERCISES[6],
        sets: [
          { reps: 12, weight: 20, rest: 60 },
          { reps: 12, weight: 20, rest: 60 },
          { reps: 10, weight: 22, rest: 60 },
        ],
      },
    ],
    duration: 55,
    difficulty: 'intermediate',
    category: 'Fuerza',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600',
    createdAt: '2024-01-20',
  },
  {
    id: 'r2',
    name: 'Piernas & Glúteos',
    description: 'Rutina completa para tren inferior con sentadillas y peso muerto.',
    trainerId: 't1',
    userId: 'u1',
    exercises: [
      {
        exerciseId: 'e2',
        exercise: MOCK_EXERCISES[1],
        sets: [
          { reps: 10, weight: 80, rest: 120 },
          { reps: 8, weight: 90, rest: 120 },
          { reps: 6, weight: 100, rest: 150 },
          { reps: 6, weight: 100, rest: 150 },
        ],
      },
      {
        exerciseId: 'e3',
        exercise: MOCK_EXERCISES[2],
        sets: [
          { reps: 8, weight: 100, rest: 150 },
          { reps: 6, weight: 110, rest: 150 },
          { reps: 5, weight: 120, rest: 180 },
        ],
      },
      {
        exerciseId: 'e6',
        exercise: MOCK_EXERCISES[5],
        sets: [
          { reps: 1, duration: 60, rest: 60 },
          { reps: 1, duration: 60, rest: 60 },
          { reps: 1, duration: 45, rest: 60 },
        ],
      },
    ],
    duration: 65,
    difficulty: 'advanced',
    category: 'Fuerza',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
    createdAt: '2024-01-25',
  },
  {
    id: 'r3',
    name: 'HIIT Cardio Quema Grasa',
    description: 'Sesión de cardio intervalado para máxima quema de calorías.',
    trainerId: 't1',
    userId: 'u2',
    exercises: [
      {
        exerciseId: 'e5',
        exercise: MOCK_EXERCISES[4],
        sets: [
          { reps: 1, duration: 30, rest: 15 },
          { reps: 1, duration: 30, rest: 15 },
          { reps: 1, duration: 30, rest: 15 },
          { reps: 1, duration: 30, rest: 15 },
          { reps: 1, duration: 30, rest: 15 },
          { reps: 1, duration: 30, rest: 15 },
          { reps: 1, duration: 30, rest: 15 },
          { reps: 1, duration: 30, rest: 15 },
        ],
      },
    ],
    duration: 30,
    difficulty: 'intermediate',
    category: 'Cardio',
    imageUrl: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=600',
    createdAt: '2024-02-01',
  },
  {
    id: 'r4',
    name: 'Full Body Principiante',
    description: 'Rutina ideal para empezar. Trabaja todo el cuerpo con ejercicios básicos.',
    trainerId: 't1',
    userId: 'u3',
    exercises: [
      {
        exerciseId: 'e6',
        exercise: MOCK_EXERCISES[5],
        sets: [
          { reps: 1, duration: 30, rest: 60 },
          { reps: 1, duration: 30, rest: 60 },
          { reps: 1, duration: 30, rest: 60 },
        ],
      },
      {
        exerciseId: 'e8',
        exercise: MOCK_EXERCISES[7],
        sets: [
          { reps: 15, weight: 8, rest: 60 },
          { reps: 15, weight: 8, rest: 60 },
          { reps: 12, weight: 10, rest: 60 },
        ],
      },
    ],
    duration: 35,
    difficulty: 'beginner',
    category: 'Full Body',
    imageUrl: 'https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=600',
    createdAt: '2024-03-05',
  },
];

// ─── WORKOUT SESSIONS ─────────────────────────────────────────────────────────
const today = new Date();
const fmt = (d: Date) => d.toISOString().split('T')[0];
const addDays = (d: Date, n: number) => {
  const r = new Date(d);
  r.setDate(r.getDate() + n);
  return r;
};

export const MOCK_SESSIONS: WorkoutSession[] = [
  {
    id: 's1',
    routineId: 'r1',
    routine: MOCK_ROUTINES[0],
    userId: 'u1',
    date: fmt(today),
    duration: 55,
    status: 'planned',
  },
  {
    id: 's2',
    routineId: 'r2',
    routine: MOCK_ROUTINES[1],
    userId: 'u1',
    date: fmt(addDays(today, -2)),
    completedAt: fmt(addDays(today, -2)),
    duration: 65,
    status: 'completed',
  },
  {
    id: 's3',
    routineId: 'r1',
    routine: MOCK_ROUTINES[0],
    userId: 'u1',
    date: fmt(addDays(today, 2)),
    duration: 55,
    status: 'planned',
  },
  {
    id: 's4',
    routineId: 'r2',
    routine: MOCK_ROUTINES[1],
    userId: 'u1',
    date: fmt(addDays(today, -5)),
    completedAt: fmt(addDays(today, -5)),
    duration: 70,
    status: 'completed',
  },
  {
    id: 's5',
    routineId: 'r3',
    routine: MOCK_ROUTINES[2],
    userId: 'u1',
    date: fmt(addDays(today, -7)),
    completedAt: fmt(addDays(today, -7)),
    duration: 30,
    status: 'completed',
  },
];

// ─── CONVERSATIONS & MESSAGES ─────────────────────────────────────────────────
export const MOCK_MESSAGES: ChatMessage[] = [
  {
    id: 'm1',
    conversationId: 'c1',
    senderId: 't1',
    text: 'Hola Alex! ¿Cómo te fue en el entrenamiento de ayer?',
    sentAt: new Date(Date.now() - 3600000).toISOString(),
    type: 'text',
  },
  {
    id: 'm2',
    conversationId: 'c1',
    senderId: 'u1',
    text: 'Muy bien Carlos! Logré completar todas las series del press de banca 💪',
    sentAt: new Date(Date.now() - 3500000).toISOString(),
    readAt: new Date(Date.now() - 3490000).toISOString(),
    type: 'text',
  },
  {
    id: 'm3',
    conversationId: 'c1',
    senderId: 't1',
    text: 'Excelente! Mañana subimos el peso en sentadilla. Te mando la rutina actualizada.',
    sentAt: new Date(Date.now() - 3400000).toISOString(),
    type: 'text',
  },
  {
    id: 'm4',
    conversationId: 'c1',
    senderId: 't1',
    text: 'Aquí está tu rutina para mañana:',
    sentAt: new Date(Date.now() - 3300000).toISOString(),
    type: 'routine',
    routineId: 'r2',
  },
  {
    id: 'm5',
    conversationId: 'c1',
    senderId: 'u1',
    text: 'Perfecto! Estaré listo. ¿A qué hora recomendás entrenar?',
    sentAt: new Date(Date.now() - 1800000).toISOString(),
    type: 'text',
  },
  {
    id: 'm6',
    conversationId: 'c1',
    senderId: 't1',
    text: 'Lo ideal es en la mañana, entre 7 y 9am. Tendrás más energía.',
    sentAt: new Date(Date.now() - 900000).toISOString(),
    type: 'text',
  },
  {
    id: 'm7',
    conversationId: 'c2',
    senderId: 't1',
    text: 'María, recuerda hidratarte bien antes del HIIT.',
    sentAt: new Date(Date.now() - 7200000).toISOString(),
    type: 'text',
  },
  {
    id: 'm8',
    conversationId: 'c2',
    senderId: 'u2',
    text: 'Claro Carlos, gracias por el recordatorio!',
    sentAt: new Date(Date.now() - 7100000).toISOString(),
    type: 'text',
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'c1',
    participants: [MOCK_USERS[0], MOCK_USERS[1]],
    lastMessage: MOCK_MESSAGES[5],
    updatedAt: new Date(Date.now() - 900000).toISOString(),
    unreadCount: 3,
  },
  {
    id: 'c2',
    participants: [MOCK_USERS[2], MOCK_USERS[1]],
    lastMessage: MOCK_MESSAGES[7],
    updatedAt: new Date(Date.now() - 7100000).toISOString(),
    unreadCount: 0,
  },
];

// ─── POSTS ────────────────────────────────────────────────────────────────────
export const MOCK_POSTS: Post[] = [
  {
    id: 'p1',
    authorId: 'u1',
    author: MOCK_USERS[0],
    text: '¡Nueva semana, nuevo récord! Logré 100kg en sentadilla por primera vez 🎉 La constancia siempre da resultados. #FitPro #Progreso',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
    likes: ['u2', 'u3', 't1'],
    comments: [
      {
        id: 'co1',
        authorId: 't1',
        author: MOCK_USERS[1],
        text: '¡Excelente trabajo Alex! Así se hace 💪',
        createdAt: new Date(Date.now() - 1800000).toISOString(),
      },
      {
        id: 'co2',
        authorId: 'u2',
        author: MOCK_USERS[2],
        text: 'Increíble progreso! Me inspiras 🔥',
        createdAt: new Date(Date.now() - 900000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'p2',
    authorId: 't1',
    author: MOCK_USERS[1],
    text: 'Tip del día: La recuperación es tan importante como el entrenamiento. Duerme 7-8 horas y notarás una diferencia enorme en tu rendimiento. 💤 #TipsEntrenamiento #FitPro',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600',
    likes: ['u1', 'u2', 'u3'],
    comments: [
      {
        id: 'co3',
        authorId: 'u3',
        author: MOCK_USERS[3],
        text: 'Gracias por el consejo, lo tendré en cuenta!',
        createdAt: new Date(Date.now() - 7200000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 'p3',
    authorId: 'u2',
    author: MOCK_USERS[2],
    text: 'Completé mi primer 5K sin parar 🏃‍♀️ Hace 3 meses apenas podía correr 1km. El progreso es real. #Running #Cardio #FitPro',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600',
    likes: ['u1', 't1'],
    comments: [],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'p4',
    authorId: 'u3',
    author: MOCK_USERS[3],
    text: 'Primer mes entrenando con Carlos. Bajé 4kg y me siento con mucha más energía. ¡Este proceso vale la pena! 💪 #Transformacion #FitPro',
    likes: ['u1', 'u2', 't1'],
    comments: [
      {
        id: 'co4',
        authorId: 't1',
        author: MOCK_USERS[1],
        text: 'Orgullo de ver tu progreso Juan! Vamos por más 🎯',
        createdAt: new Date(Date.now() - 172800000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
];

// ─── PAYMENTS ─────────────────────────────────────────────────────────────────
export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 'pay1',
    userId: 'u1',
    amount: 50,
    currency: 'USD',
    status: 'validated',
    plan: 'Plan Premium - Mensual',
    date: '2026-01-15',
    dueDate: '2026-02-15',
  },
  {
    id: 'pay2',
    userId: 'u1',
    amount: 50,
    currency: 'USD',
    status: 'pending',
    plan: 'Plan Premium - Mensual',
    date: '2026-02-15',
    dueDate: '2026-03-15',
  },
  {
    id: 'pay3',
    userId: 'u2',
    amount: 50,
    currency: 'USD',
    status: 'validated',
    plan: 'Plan Premium - Mensual',
    date: '2026-01-10',
    dueDate: '2026-02-10',
  },
  {
    id: 'pay4',
    userId: 'u3',
    amount: 50,
    currency: 'USD',
    status: 'rejected',
    plan: 'Plan Premium - Mensual',
    date: '2026-02-01',
    dueDate: '2026-03-01',
  },
];

export const MOCK_PLANS: Plan[] = [
  {
    id: 'pl1',
    name: 'Plan Básico',
    price: 25,
    currency: 'USD',
    period: 'monthly',
    features: ['Acceso a rutinas básicas', 'Feed social', 'Calendario fitness'],
    isActive: false,
  },
  {
    id: 'pl2',
    name: 'Plan Premium',
    price: 50,
    currency: 'USD',
    period: 'monthly',
    features: [
      'Todo del plan básico',
      'Entrenador personal asignado',
      'Chat con entrenador',
      'Rutinas personalizadas',
      'Biblioteca completa de ejercicios',
      'Seguimiento detallado',
    ],
    isActive: true,
  },
  {
    id: 'pl3',
    name: 'Plan Anual',
    price: 480,
    currency: 'USD',
    period: 'annual',
    features: [
      'Todo del plan premium',
      '2 meses gratis',
      'Acceso prioritario a nuevas funciones',
      'Soporte dedicado',
    ],
    isActive: false,
  },
];

// ─── CALENDAR ─────────────────────────────────────────────────────────────────
export const MOCK_CALENDAR: CalendarDay[] = [
  { date: fmt(addDays(today, -7)), hasWorkout: true, workoutId: 's5', workoutName: 'HIIT Cardio', status: 'completed' },
  { date: fmt(addDays(today, -5)), hasWorkout: true, workoutId: 's4', workoutName: 'Piernas & Glúteos', status: 'completed' },
  { date: fmt(addDays(today, -2)), hasWorkout: true, workoutId: 's2', workoutName: 'Fuerza Superior A', status: 'completed' },
  { date: fmt(today), hasWorkout: true, workoutId: 's1', workoutName: 'Fuerza Superior A', status: 'planned' },
  { date: fmt(addDays(today, 2)), hasWorkout: true, workoutId: 's3', workoutName: 'Piernas & Glúteos', status: 'planned' },
  { date: fmt(addDays(today, 4)), hasWorkout: true, workoutName: 'HIIT Cardio', status: 'planned' },
  { date: fmt(addDays(today, 7)), hasWorkout: true, workoutName: 'Fuerza Superior A', status: 'planned' },
];
